# Generated by Django 5.0.7 on 2024-08-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The contributor's first named.", max_length=50)),
                ('last_name', models.CharField(help_text="The contributor's last named.", max_length=50)),
                ('email', models.EmailField(help_text='The contact Email for the contributor.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text=" The Publisher's website.")),
                ('email', models.EmailField(help_text='Thw Publisher Email.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MovieContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=20, verbose_name='The role this contributor has in the movie.')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This name Of the Movie', max_length=100)),
                ('date', models.DateField(verbose_name='Date the movie was released')),
                ('contributors', models.ManyToManyField(through='MoviesListApp.MovieContributor', to='MoviesListApp.contributor')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='moviecontributor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The Review text.')),
                ('rating', models.IntegerField(help_text='The rating the revviewer has given.')),
                ('data_created', models.DateTimeField(auto_now_add=True, help_text='The date and time review was created.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(help_text='The Movie that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.movies_info')),
            ],
        ),
    ]
